"""Execute the Colab notebook end-to-end with a tiny workload (GS4D_NOTEBOOK_TEST=1)."""

import importlib.util
import os
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks" / "tree_wind_4dgs_demo.ipynb"

pytestmark = pytest.mark.skipif(
    importlib.util.find_spec("nbclient") is None or importlib.util.find_spec("ipykernel") is None,
    reason="nbclient / ipykernel not installed",
)


def test_notebook_runs(monkeypatch):
    import nbformat
    from nbclient import NotebookClient

    monkeypatch.setenv("GS4D_NOTEBOOK_TEST", "1")
    nb = nbformat.read(NB, as_version=4)
    NotebookClient(nb, timeout=600, kernel_name="python3", resources={"metadata": {"path": str(NB.parent)}}).execute()
    errors = [o for c in nb.cells if c.cell_type == "code" for o in c.get("outputs", []) if o.output_type == "error"]
    assert not errors
    export = ROOT / "outputs" / "tree_wind"
    assert (export / "ply_sequence" / "tree_wind_0001.ply").exists()
    assert (export / "gs4d_import_sequence.py").exists()
    assert (ROOT / "outputs" / "preview.mp4").stat().st_size > 1000
    assert (ROOT / "outputs" / "tree_wind.zip").exists()


def test_notebook_is_clean():
    """The committed notebook has no outputs (it is generated by scripts/build_notebook.py)."""
    import nbformat

    nb = nbformat.read(NB, as_version=4)
    assert all(not c.get("outputs") for c in nb.cells if c.cell_type == "code")
    assert nb.metadata.get("accelerator") == "GPU"
    assert os.path.exists(ROOT / "scripts" / "build_notebook.py")
